config/routes.rb
Rails.application.routes.draw do
  # resources :restaurants, only: [:index, :show]
  resources :restaurants do
    # GET /restaurants/:restaurant_id/reviews/new => reviews#new
    resources :reviews, only:[ :new, :create ]
    collection do
      # GET /restaurants/top => restaurants#top
      get :top
    end
    member do
      get :chef
    end
  end

  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # GET /restaurants/:id/chef
  def chef
    # Grab the restaurant using params[:id]
    @restaurant = Restaurant.find(params[:id])
    # Grab the chef info for this restaurant
    @chef_name = @restaurant.chef_name

    # render "restaurants/chef.html.erb"
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
  end

  def top
    # Grab all 5 star restaurants
    @restaurants = Restaurant.where(rating: 5)
    # render 'restaurants/top.html.erb'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  # GET /restaurants/:restaurant_id/reviews/new
  def new
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  # POST /restaurants/:restaurant_id/reviews
  def create
    # get the restaurant with params[:restaurant_id]
    # @restaurant = Restaurant.find(params[:restaurant_id])
    # create the review with content from form
    @review = Review.new(review_params)
    # Add the resatruant to review
    @review.restaurant = @restaurant
    # save it
    if @review.save
      # redirect to the restaurant show page
      redirect_to restaurant_path(@restaurant), notice: "Successfully created review 🎉"
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  # DELETE /reviews/:id
  def destroy
    # find the review
    @review = Review.find(params[:id])
    # destroy the review
    @review.destroy
    # redirect to wherever we want (restaurant show page)
    redirect_to restaurant_path(@review.restaurant), notice: "Successfully destroyed review", status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeyondCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= restaurant.rating %>
  </p>

</div>

app/views/restaurants/chef.html.erb
<h1><%= @restaurant.name %>'s Chef</h1>
<p><%= @chef_name %></p>
<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>
  <%= link_to "See chef", chef_restaurant_path(@restaurant) %>
  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

<div class="mt-4">
  <h2>Reviews</h2>
  <%= link_to 'Create review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary'  %>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content %> |
          <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="red" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"></rect><path d="M216,48H176V40a24.1,24.1,0,0,0-24-24H104A24.1,24.1,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM112,168a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm0-120H96V40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8Z"></path></svg>
          <% end %>
        </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/top.html.erb
<p style="color: green"><%= notice %></p>

<h1>5 star Restaurants ⭐️⭐️⭐️⭐️⭐️</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1>Create a review for <%= @restaurant.name %></h1>

<%= simple_form_for([ @restaurant, @review ]) do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex align-items-center justify-content-between p-4 border">
  <p>Best restaurants</p>
  <div class="d-flex align-items-center justify-content-between">
    <%= link_to 'All Restaurants', restaurants_path, class: 'ms-2' %>
    <%= link_to 'Top Restaurants', top_restaurants_path, class: 'ms-2' %>
  </div>
</div>